### ISSUE TITLE
Práctica 5 Modelo de Negocios en Bizagi Web 2.0

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-hjfs#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 5 de modelado de negocio en Bpmn en Architect o Bizagi (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-hjfs/files/9603296/Practica.5.de.modelado.de.negocio.en.Bpmn.en.Architect.o.Bizagi.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 5 de modelado de negocio - Heidi Lucy Bautista Sanjuan 5USC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-hjfs/files/9603354/Practica.5.de.modelado.de.negocio.-.Heidi.Lucy.Bautista.Sanjuan.5USC.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 5 de modelado de negocio en Bizagi(José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-hjfs/files/9603541/Practica.5.de.modelado.de.negocio.en.Bizagi.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by SANDRAVELASCO** [comment]
[Práctica 5 de modelado de negocio en Bpmn en Architect o Bizagi.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-hjfs/files/9618864/Practica.5.de.modelado.de.negocio.en.Bpmn.en.Architect.o.Bizagi.pdf)

**Comment by Elisahadad** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
